name: nutri_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.3.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    shared_preferences: ^2.2.0
    fl_chart: ^0.71.0
    lucide_icons_flutter: ^3.0.0
    logger: ^0.7.0+2
    path_provider: ^2.1.1
    path: ^1.8.0
    intl: ^0.20.2
    diacritic: ^0.1.3
    http: ^1.1.0
    firebase_core: ^2.24.2
    cloud_firestore: ^4.13.5
    firebase_auth: ^4.17.5
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    flutter_dotenv: ^5.1.0
    icalendar_parser: ^2.0.1
    web: ^0.4.0
    flutter_riverpod: ^2.5.1
    equatable: ^1.0.1
    url_launcher: ^6.2.6
    characters: ^1.3.0
    crypto: ^3.0.3
    provider_architecture: ^1.0.3
    responsive_builder: ^0.1.4
    provider: ^3.2.0
    get_it: ^3.0.3
flutter:
    uses-material-design: true
    assets:
        - assets/food_data.json
        - assets/env.json
        - assets/poids_usuel.json
        - assets/.env
        - assets/icons/Icon-512.png
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    build_runner: ^2.4.6
    hive_generator: ^2.0.1


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages