name: nutri_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  fl_chart: ^0.71.0
  lucide_icons_flutter: ^3.0.0
  logger: ^2.0.2
  path_provider: ^2.1.1
  path: ^1.8.0
  intl: ^0.20.2
  diacritic: ^0.1.3
  http: ^1.1.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.17.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0
  icalendar_parser: ^2.0.1
  web: ^0.4.0
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  url_launcher: ^6.2.6
  characters: ^1.3.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/food_data.json
    - assets/env.json
    - assets/poids_usuel.json
    - .env
    - assets/icons/Icon-512.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
