// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbvXisAiG316lMoOpbVj8uLLnlyMyt7MQ',
    appId: '1:84884488780:web:0f0c8ace45e9e29a36aae9',
    messagingSenderId: '84884488780',
    projectId: 'nutriapp-4ea20',
    authDomain: 'nutriapp-4ea20.firebaseapp.com',
    storageBucket: 'nutriapp-4ea20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJzIeyLqSHG3NPE90oGX6VaOMcvsZ796U',
    appId: '1:84884488780:android:c8cef5fa552e4f7036aae9',
    messagingSenderId: '84884488780',
    projectId: 'nutriapp-4ea20',
    storageBucket: 'nutriapp-4ea20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNW4fEij1dmfPVyyPhadbCkzFphCeZOTI',
    appId: '1:84884488780:ios:bfedf07e96c2a09c36aae9',
    messagingSenderId: '84884488780',
    projectId: 'nutriapp-4ea20',
    storageBucket: 'nutriapp-4ea20.firebasestorage.app',
    iosBundleId: 'com.example.nutriApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNW4fEij1dmfPVyyPhadbCkzFphCeZOTI',
    appId: '1:84884488780:ios:d70f34f0782162b836aae9',
    messagingSenderId: '84884488780',
    projectId: 'nutriapp-4ea20',
    storageBucket: 'nutriapp-4ea20.firebasestorage.app',
    iosBundleId: 'com.example.nutriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbvXisAiG316lMoOpbVj8uLLnlyMyt7MQ',
    appId: '1:84884488780:web:0f0c8ace45e9e29a36aae9',
    messagingSenderId: '84884488780',
    projectId: 'nutriapp-4ea20',
    authDomain: 'nutriapp-4ea20.firebaseapp.com',
    storageBucket: 'nutriapp-4ea20.firebasestorage.app',
  );

}